const menuButton=document.querySelector('.mobile-menu');
const menu=document.querySelector('#mobile-nav');
menuButton.addEventListener('click',()=>{const open=menu.hidden;menu.hidden=!open;menuButton.setAttribute('aria-expanded',String(open));menuButton.setAttribute('aria-label',open?'Stäng meny':'Öppna meny');});
menu.addEventListener('click',e=>{if(e.target.closest('a')){menu.hidden=true;menuButton.setAttribute('aria-expanded','false');menuButton.setAttribute('aria-label','Öppna meny');}});
const motion=matchMedia('(prefers-reduced-motion: reduce)');
const animations=new Set();let observer;
function enableMotion(){observer?.disconnect();animations.forEach(a=>a.cancel());animations.clear();if(motion.matches||!('IntersectionObserver' in window))return;observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(!entry.isIntersecting)return;observer.unobserve(entry.target);const a=entry.target.animate([{opacity:.6,transform:'translateY(12px)',filter:'blur(2px)'},{opacity:1,transform:'translateY(0)',filter:'blur(0)'}],{duration:850,easing:'cubic-bezier(.2,.75,.25,1)'});animations.add(a);a.onfinish=()=>animations.delete(a);});},{threshold:.08});document.querySelectorAll('[data-reveal]').forEach(el=>observer.observe(el));}
enableMotion();motion.addEventListener('change',enableMotion);
let classes=[],period='all';const category=document.querySelector('#category-filter'),results=document.querySelector('#class-results'),dialog=document.querySelector('#class-detail');
function node(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
function swedishNow(){return new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Stockholm',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date()).replace(' ','T');}
function label(value){return new Intl.DateTimeFormat('sv-SE',{weekday:'long',day:'numeric',month:'long',timeZone:'UTC'}).format(new Date(value.slice(0,10)+'T12:00:00Z'));}
function showDetail(c){const body=document.querySelector('#detail-body');body.replaceChildren();const title=node('h2',c.title);title.id='detail-title';dialog.setAttribute('aria-labelledby',title.id);body.append(node('p',c.category,'eyebrow'),title,node('p',label(c.starts_at)),node('p',c.starts_at.slice(11)+' · '+c.duration+' min'),node('p',c.location),node('p',c.description),node('p',c.price));if(c.status==='cancelled')body.append(node('p','Det här passet är inställt.'));else{const a=node('a',c.booking_url?'Till bokningen':'Ring för att boka','button');a.href=c.booking_url||'tel:0739334254';if(c.booking_url){a.target='_blank';a.rel='noopener noreferrer';}body.append(a);}dialog.showModal();}
document.querySelector('#close-detail').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
function render(){const now=swedishNow();const end=new Date(now.slice(0,10)+'T12:00:00Z');end.setUTCDate(end.getUTCDate()+7);const limit=end.toISOString().slice(0,10);const visible=classes.filter(c=>c.starts_at>=now&&(category.value==='all'||category.value===c.category)&&(period==='all'||(period==='today'?c.starts_at.slice(0,10)===now.slice(0,10):c.starts_at.slice(0,10)<limit)));results.replaceChildren();results.className=visible.length?'timeline':'schedule-empty';if(!visible.length){results.append(node('h3','Inga kommande pass för ditt val'),node('p','Kontakta Maya för aktuella träningstillfällen.'));const link=node('a','Mejla Maya','text-link');link.href='mailto:mayahaglund@outlook.com';results.append(link);return;}for(const day of [...new Set(visible.map(c=>c.starts_at.slice(0,10)))]){const group=node('div',undefined,'timeline-day');const date=node('div',undefined,'day-label');date.append(node('span',String(Number(day.slice(8)))),node('p',label(day)));const list=node('div',undefined,'day-classes');for(const c of visible.filter(c=>c.starts_at.startsWith(day))){const row=node('button',undefined,'class-row'+(c.status==='cancelled'?' cancelled':''));row.type='button';const time=node('div',c.starts_at.slice(11),'class-time');time.append(node('span',c.duration+' min'));const info=node('div',undefined,'class-info');info.append(node('span',c.category,'class-category'),node('h3',c.title),node('p',c.location));row.append(time,info,node('span',c.status==='cancelled'?'Inställt':c.price||'Se detaljer','class-status'));row.addEventListener('click',()=>showDetail(c));list.append(row);}group.append(date,list);results.append(group);}}
document.querySelectorAll('[data-period]').forEach(b=>b.addEventListener('click',()=>{period=b.dataset.period;document.querySelectorAll('[data-period]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));render();}));category.addEventListener('change',render);
fetch('./classes.json').then(r=>{if(!r.ok)throw Error();return r.json();}).then(data=>{classes=data.classes.filter(c=>['published','cancelled'].includes(c.status)).sort((a,b)=>a.starts_at.localeCompare(b.starts_at));for(const c of [...new Set(classes.map(c=>c.category))]){const option=node('option',c);option.value=c;category.append(option);}render();}).catch(()=>{results.replaceChildren(node('h3','Schemat kunde inte hämtas'),node('p','Kontakta Maya på mayahaglund@outlook.com för aktuella pass.'));});
