export type TrainingPackage={id:string;title:string;category:string;price:string;unit:string;description:string;published:boolean};
export const fieldGroups = {
 'Varumärke & kontakt': { name:'Namn', role:'Yrkesroll', phone:'Telefonnummer',email:'Primär e-postadress', instagram:'Instagram-länk', facebook:'Facebook-länk', footer:'Text i sidfoten', seoTitle:'Sidtitel i sökresultat', seoDescription:'Beskrivning i sökresultat' },
 'Meny & knappar': {navTraining:'Meny: träning',navPackages:'Meny: paket',navSchedule:'Meny: schema',navAbout:'Meny: om',navContact:'Meny: kontakt',navCta:'Knapp i menyn',cta:'Huvudknapp',call:'Ring-knapp'},
 'Startsida': {heroEyebrow:'Överrubrik',heroLine1:'Rubrik rad 1',heroLine2:'Rubrik rad 2',heroLine3:'Rubrik rad 3',heroIntro:'Introduktion',heroMicro:'Text under knappen',heroPhotoLabel:'Bildens överrubrik',heroPhotoText:'Bildens rubrik',heroBadge:'Rund etikett',principle1:'Ledord 1',principle2:'Ledord 2',principle3:'Ledord 3'},
 'Träningsformer': {servicesEyebrow:'Överrubrik',servicesTitle:'Rubrik',servicesIntro:'Introduktion'},
 'Pass & schema': {scheduleEyebrow:'Överrubrik',scheduleTitle:'Rubrik',scheduleIntro:'Introduktion',scheduleEmpty:'Text när inga pass är publicerade'},
 'Paket & priser': {packagesEyebrow:'Överrubrik',packagesTitle:'Rubrik',packagesIntro:'Introduktion',packageCta:'Länktext på paketen',packageNoPrice:'Text när pris saknas'},
 'Om Maya': {aboutEyebrow:'Överrubrik',aboutTitle:'Rubrik',aboutLead:'Inledning',aboutText:'Presentation',aboutText2:'Fortsättning',aboutCta:'Länktext'},
 'Så går det till': {processEyebrow:'Överrubrik',processTitle:'Rubrik',processIntro:'Introduktion'},
 'Kontaktsektion': {contactEyebrow:'Överrubrik',contactTitle:'Rubrik',contactText:'Beskrivning',contactPlace:'Plats'}
} as const;
export const defaultContent = {
 text: {navPackages:'Paket & priser',packagesEyebrow:'TRÄNING SOM PASSAR DIG',packagesTitle:'Paket & priser.',packagesIntro:'Hitta ditt upplägg. Hör av dig till Maya om du vill ha hjälp att välja.',packageCta:'Fråga om paketet',packageNoPrice:'Kontakta för pris',name:'Maya Haglund',role:'Personlig tränare',phone:'0739-33 42 54',email:'mayahaglund@outlook.com',instagram:'https://www.instagram.com/ptmayamolin',facebook:'https://www.facebook.com/102039771897462',footer:'Starkare, på ditt sätt.',seoTitle:'Maya Haglund | Personlig träning i Lysekil',seoDescription:'Personlig träning, PT Duo och gruppträning med Maya Haglund i Lysekil. Se kommande pass och hör av dig för en kostnadsfri konsultation.',navTraining:'Träna med mig',navSchedule:'Kommande pass',navAbout:'Om Maya',navContact:'Kontakt',navCta:'Låt oss börja',cta:'Boka en fri konsultation',call:'Ring Maya',heroEyebrow:'PERSONLIG TRÄNING I LYSEKIL',heroLine1:'Starkare.',heroLine2:'Tryggare.',heroLine3:'Mer du.',heroIntro:'Du behöver inte ha allt på plats för att börja. Vi hittar träningen som passar dig, dina mål och ditt liv.',heroMicro:'Ditt första steg. I din takt.',heroPhotoLabel:'DIN TRÄNING. DINA FÖRUTSÄTTNINGAR.',heroPhotoText:'Vi börjar där\ndu är.',heroBadge:'Plats för dig.',principle1:'Träning på dina villkor',principle2:'Personlig vägledning',principle3:'Glädje i rörelse',servicesEyebrow:'HITTA DITT SÄTT',servicesTitle:'Din väg till\nen starkare vardag.',servicesIntro:'På egen hand, tillsammans med någon eller i grupp. Vi hittar ett upplägg för dig.',scheduleEyebrow:'GÖR PLATS FÖR DIG',scheduleTitle:'Vi ses på nästa pass.',scheduleIntro:'Hitta din nästa stund av rörelse. Här ser du kommande pass, tider och platser.',scheduleEmpty:'Nya pass är på gång. Hör av dig till Maya för aktuella träningstillfällen.',aboutEyebrow:'DIN TRÄNARE, MAYA HAGLUND',aboutTitle:'En människa.\nInte en träningsmall.',aboutLead:'Bra träning börjar med dig.',aboutText:'Det är dina förutsättningar, önskemål och mål som formar våra pass. Oavsett om du vill komma igång eller hitta ett nytt sätt att träna, börjar vi med att prata om vad du behöver.',aboutText2:'Som personlig tränare och utbildad gruppträningsinstruktör hjälper jag både enskilda och grupper att hitta sitt sätt att röra sig.',aboutCta:'Säg hej, så tar vi det därifrån',processEyebrow:'FRÅN TANKE TILL TRÄNING',processTitle:'Det börjar med\nett samtal.',processIntro:'Du behöver inte veta exakt vad du vill. Det tar vi reda på tillsammans.',contactEyebrow:'REDO NÄR DU ÄR',contactTitle:'Lite nyfiken?\nDet räcker.',contactText:'Hör av dig till mig för en kostnadsfri konsultation. Berätta lite om dig, så hittar vi en början.',contactPlace:'LYSEKIL, VÄSTKUSTEN'} as Record<string,string>,
 packages:[
 {id:'pt-3',title:'3 träningspass',category:'Personlig träning',price:'2 100',unit:'kr / paket',description:'Tre individuellt anpassade träningspass på gym inklusive uppföljning. Fri konsultation ingår.',published:true},
 {id:'pt-5',title:'5 träningspass',category:'Personlig träning',price:'3 250',unit:'kr / paket',description:'Fem individuellt anpassade träningspass på gym inklusive uppföljning. Fri konsultation ingår.',published:true},
 {id:'pt-10',title:'10 träningspass',category:'Personlig träning',price:'6 000',unit:'kr / paket',description:'Tio individuellt anpassade träningspass på gym inklusive uppföljning. Fri konsultation ingår.',published:true},
 {id:'duo-5',title:'5 träningspass tillsammans',category:'PT Duo',price:'2 250',unit:'kr / person',description:'Fem anpassade träningspass på gym inklusive uppföljning. Fri konsultation ingår.',published:true},
 {id:'duo-10',title:'10 träningspass tillsammans',category:'PT Duo',price:'4 000',unit:'kr / person',description:'Tio anpassade träningspass på gym inklusive uppföljning. Fri konsultation ingår.',published:true},
 {id:'group-hour',title:'Företag, förening & event',category:'Gruppträning',price:'1 000',unit:'kr / timme',description:'Träning efter överenskommelse. Lägre pris vid återkommande aktiviteter eller pass. Betalning via bankgiro enligt faktura.',published:true},
 {id:'gift',title:'Ge bort träning',category:'Presentkort',price:'',unit:'',description:'Ge bort PT-timmar till någon du tycker om. Kontakta Maya för att ordna ett presentkort.',published:true},
 {id:'online',title:'Online PT',category:'Online PT',price:'',unit:'kr / månad',description:'',published:false}
 ] as TrainingPackage[],
 images:{hero:'/assets/maya.jpg',heroAlt:'Bohusläns klippor och hav vid Lysekil'},
 services:[{id:'pt',title:'Personlig träning',text:'Träningspass anpassade efter dina mål och förutsättningar. Med vägledning som hjälper dig att känna dig trygg i träningen.',image:'/assets/pt.jpg',alt:'Personlig träning med vikter',tag:'DITT EGET FOKUS',cta:'Hitta ditt upplägg'}, {id:'duo',title:'PT Duo',text:'Ta med en vän, partner eller kollega. Träna tillsammans med ett upplägg som tar hänsyn till er båda.',image:'/assets/duo.jpg',alt:'Träning tillsammans i gymmet',tag:'STARKARE TILLSAMMANS',cta:'Träna som duo'}, {id:'group',title:'Grupp & förening',text:'Samla gruppen kring rörelse. Enstaka aktiviteter eller återkommande pass för föreningar och andra verksamheter.',image:'/assets/group.jpg',alt:'Gemensam gruppträning utomhus',tag:'ENERGI I GEMENSKAP',cta:'Planera ett pass'}],
 steps:[{title:'Vi lär känna dig',text:'Vi börjar med en kostnadsfri konsultation om dina mål, din vardag och vad du vill få ut av träningen.'},{title:'Vi hittar ditt upplägg',text:'Tillsammans pratar vi igenom träningsform och omfattning. Du får information om pris innan du bestämmer dig.'},{title:'Du tar nästa steg',text:'När du bokar personlig träning får du anpassade pass att följa. Vi börjar på din nivå.'}]
};
export type SiteContent=typeof defaultContent;
export type ClassItem={id:string;title:string;category:string;starts_at:string;duration:number;location:string;description:string;price:string;booking_url:string;status:'draft'|'published'|'cancelled';version:number;updated_at:string};
export function stockholmNow(){return new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Stockholm',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date()).replace(' ','T');}
export function dateLabel(value:string){return new Intl.DateTimeFormat('sv-SE',{weekday:'long',day:'numeric',month:'long',timeZone:'UTC'}).format(new Date(value.slice(0,10)+'T12:00:00Z'));}
export function phoneHref(phone:string){return 'tel:'+phone.replace(/[^+\d]/g,'');}
