import type {Config} from '@netlify/functions';
import {getStore,getDeployStore} from '@netlify/blobs';
import {valid,cors} from '../auth';
import {defaultContent,stockholmNow,type SiteContent,type ClassItem} from '../../lib/content';
import {contentSchema,classSchema} from '../../lib/validation';
import {classDates} from '../../lib/recurrence';
import seedContent from '../seed-content.json';
import seedClasses from '../seed-classes.json';
type State={draft:{content:SiteContent;version:number};published:{content:SiteContent;version:number};classes:ClassItem[]};
function store(){return Netlify.context?.deploy.context==='production'?getStore({name:'maya-content',consistency:'strong'}):getDeployStore({name:'maya-content',consistency:'strong'});}
function initial():State{const content={...defaultContent,...seedContent.content,text:{...defaultContent.text,...seedContent.content.text}};return {draft:{content,version:1},published:{content,version:1},classes:seedClasses.classes.map(c=>({...c,version:1,updated_at:new Date().toISOString()})) as ClassItem[]};}
class Problem extends Error{constructor(public status:number,message:string){super(message);}}
export default async(req:Request)=>{const headers=cors(req);if(!headers)return new Response(null,{status:403});const json=(v:unknown,status=200)=>Response.json(v,{status,headers});if(req.method==='OPTIONS')return new Response(null,{status:204,headers});try{
 const url=new URL(req.url),path=url.pathname;const secret=Netlify.env.get('SESSION_SECRET');const authenticated=!!secret&&valid((req.headers.get('authorization')||'').replace(/^Bearer /,''),secret);
 const needsAuth=req.method!=='GET'||path==='/api/admin'||url.searchParams.has('draft')||url.searchParams.has('admin');if(needsAuth&&!authenticated)throw new Problem(401,'Logga in igen för att fortsätta.');
 if(path==='/api/admin')return json({user:{email:'Maya',role:'owner'},admins:[]});
 const dataStore=store();
 if(path.startsWith('/api/media/')){if(req.method!=='GET')throw new Problem(405,'Metoden stöds inte.');const key=path.slice(11);if(!/^[a-f0-9-]+\.(jpg|png|webp)$/.test(key))throw new Problem(404,'Bilden finns inte.');const image=await dataStore.get('media/'+key,{type:'arrayBuffer'});if(!image)throw new Problem(404,'Bilden finns inte.');return new Response(image,{headers:{...headers,'Content-Type':key.endsWith('.jpg')?'image/jpeg':key.endsWith('.png')?'image/png':'image/webp','Cache-Control':'public,max-age=31536000,immutable'}});}
 if(path==='/api/upload'){if(req.method!=='POST')throw new Problem(405,'Metoden stöds inte.');if(Number(req.headers.get('content-length'))>5300000)throw new Problem(413,'Bilden får vara högst 5 MB.');const f=(await req.formData()).get('file');if(!(f instanceof File)||f.size>5000000||!f.size)throw new Problem(400,'Välj en bild på högst 5 MB.');const bytes=new Uint8Array(await f.arrayBuffer());let ext='';if(bytes[0]===255&&bytes[1]===216&&bytes[2]===255)ext='jpg';else if([137,80,78,71,13,10,26,10].every((v,i)=>bytes[i]===v))ext='png';else if(new TextDecoder().decode(bytes.slice(0,4))==='RIFF'&&new TextDecoder().decode(bytes.slice(8,12))==='WEBP')ext='webp';if(!ext)throw new Problem(400,'Använd JPG, PNG eller WebP.');const key=crypto.randomUUID()+'.'+ext;await dataStore.set('media/'+key,bytes.buffer);return json({url:'/api/media/'+key});}
 const row=await dataStore.getWithMetadata('state',{type:'json'});const state:State=row?.data||initial();
 if(req.method==='GET'){if(path==='/api/content')return json(url.searchParams.has('draft')?state.draft:state.published);if(path==='/api/classes')return json({classes:url.searchParams.has('admin')?state.classes:state.classes.filter(c=>c.status!=='draft'&&c.starts_at>=stockholmNow()).sort((a,b)=>a.starts_at.localeCompare(b.starts_at))});throw new Problem(404,'Sidan finns inte.');}
 const text=await req.text();if(text.length>150000)throw new Problem(413,'Innehållet är för stort.');let b;try{b=JSON.parse(text);}catch{throw new Problem(400,'Ogiltiga uppgifter.');}let result:unknown={ok:true};
 if(path==='/api/content'&&req.method==='POST'){const parsed=contentSchema.safeParse(b.content);if(!parsed.success)throw new Problem(400,'Kontrollera fälten: '+parsed.error.issues[0]?.message);if(b.version!==state.draft.version)throw new Problem(409,'Utkastet har ändrats. Kopiera dina ändringar och ladda om.');state.draft={content:parsed.data as SiteContent,version:state.draft.version+1};result={version:state.draft.version};}
 else if(path==='/api/content'&&req.method==='PUT'){if(b.version!==state.draft.version)throw new Problem(409,'Utkastet har ändrats. Spara igen.');state.published=structuredClone(state.draft);}
 else if(path==='/api/classes'&&req.method==='POST'){const parsed=classSchema.safeParse(b);if(!parsed.success)throw new Problem(400,'Kontrollera passet: '+parsed.error.issues[0]?.message);const c=parsed.data;const now=new Date().toISOString();if(c.id){const index=state.classes.findIndex(x=>x.id===c.id&&x.version===c.version);if(index<0)throw new Problem(409,'Passet har ändrats eller tagits bort. Ladda om.');state.classes[index]={...state.classes[index],...c,version:c.version!+1,updated_at:now};}else{const dates=classDates(c.starts_at,c.recurrence,c.repeat);if(state.classes.length+dates.length>2000)throw new Problem(400,'Ta bort gamla pass innan du lägger till fler.');const {recurrence,repeat,...fields}=c;const rows=dates.map(date=>({...fields,id:crypto.randomUUID(),starts_at:date,version:1,updated_at:now}));state.classes.push(...rows);result={ids:rows.map(x=>x.id)};}}
 else if(path==='/api/classes'&&req.method==='DELETE'){const index=state.classes.findIndex(c=>c.id===b.id&&c.version===b.version);if(index<0)throw new Problem(409,'Passet har ändrats. Ladda om.');state.classes.splice(index,1);}
 else throw new Problem(405,'Metoden stöds inte.');
 const written=await dataStore.setJSON('state',state,row?{onlyIfMatch:row.etag}:{onlyIfNew:true});if(!written.modified)throw new Problem(409,'Någon sparade samtidigt. Ladda om och försök igen.');return json(result);
 }catch(e){if(e instanceof Problem)return json({error:e.message},e.status);console.error('Storage request failed',e);return json({error:'Det gick inte att nå lagringen. Dina ändringar är kvar här. Försök igen.'},503);}};
export const config:Config={path:['/api/admin','/api/content','/api/classes','/api/upload','/api/media/*']};
