import React,{useEffect,useState,lazy,Suspense} from 'react';
import {createRoot} from 'react-dom/client';
import Website from './app/website';
const Dashboard=lazy(()=>import('./app/admin/dashboard'));
import {defaultContent,stockholmNow,type SiteContent} from './lib/content';
import {apiFetch,base,setToken,assetUrl} from './lib/client-api';
import './app/globals.css';import './app/site.css';import './app/dashboard.css';import './app/boutique.css';
function App(){const isAdmin=location.pathname.replace(/\/$/,'').endsWith('/admin');const preview=new URLSearchParams(location.search).has('preview');const [auth,setAuth]=useState(false),[checking,setChecking]=useState(isAdmin),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[content,setContent]=useState<SiteContent|null>(null);
useEffect(()=>{if(isAdmin){apiFetch('/api/admin').then(r=>{setAuth(r.ok);setChecking(false);}).catch(()=>{setChecking(false);setError('Kunde inte nå administrationen. Försök igen.');});}else{apiFetch('/api/content'+(preview?'?draft=1':'')).then(async r=>{if(!r.ok)throw Error(preview?'Logga in i admin för att visa utkastet.':'Kunde inte hämta innehållet.');return r.json();}).then(d=>setContent(d.content)).catch(e=>setError(e.message));}},[]);
async function login(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await apiFetch('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})});if(r.status===429)throw Error('För många försök. Vänta en minut och försök igen.');const d=await r.json();if(!r.ok)throw Error(d.error||'Inloggningen misslyckades.');setToken(d.token);setPassword('');setAuth(true);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
if(isAdmin){if(auth)return <Suspense fallback={<div className="admin-gate">Hämtar administrationen…</div>}><Dashboard email="Maya"/></Suspense>;return <main className="admin-gate"><a className="brand" href={base}><span className="brand-symbol"><img src={assetUrl('/assets/maya-logo.png')} alt="" width={48} height={48}/></span><span className="brand-wordmark">maya haglund<span>ADMINISTRATION</span></span></a><form className="gate-card" onSubmit={login}><p className="eyebrow">DIN WEBBPLATS</p><h1>Välkommen in.</h1>{checking?<p>Kontrollerar inloggning…</p>:<><label className="field"><span>Adminkod</span><input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<p role="alert">{error}</p>}<button className="admin-button" disabled={busy}>{busy?'Loggar in…':'Logga in'}</button></>}<a className="gate-back" href={base}>Till hemsidan</a></form></main>;}
if(!content)return <main className="admin-gate"><h1>Maya Haglund</h1><p role="status">{error||'Hämtar hemsidan…'}</p>{error&&<><button className="button" onClick={()=>location.reload()}>Försök igen</button><a href="mailto:mayahaglund@outlook.com">Mejla Maya</a></>}</main>;
return <Website content={content} now={stockholmNow()} preview={preview} unavailable={false}/>;}
createRoot(document.getElementById('root')!).render(<App/>);
