'use client';
import {apiFetch,assetUrl,base} from '@/lib/client-api';
import {useEffect,useState} from 'react';
import {type SiteContent,type ClassItem,dateLabel,phoneHref} from '@/lib/content';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {CalendarDays,MapPin,Clock,ArrowUpRight,ArrowDown,Menu,X,Target,Heart,Compass,Activity,Phone,Camera,ExternalLink,Mail,Check} from 'lucide-react';
import {useMotion} from './use-motion';
export default function Website({content:c,now,preview,unavailable}:{content:SiteContent;now:string;preview:boolean;unavailable:boolean}){
const motionRoot=useMotion();const t=c.text;const packages=c.packages.filter(p=>p.published);const [menu,setMenu]=useState(false);return <div className="public-site" ref={motionRoot}>
{preview&&<div className="preview-banner">Förhandsvisning av sparat utkast. <a href={base+'admin/'}>Tillbaka till administrationen <ArrowUpRight size={16} aria-hidden="true"/></a></div>}
{unavailable&&<div role="status" className="preview-banner">Innehållet kan inte uppdateras just nu. Försök igen om en stund.</div>}
<a className="skip" href="#main">Till innehållet</a><header className="header wrap"><a className="brand" href="#"><span className="brand-symbol"><img src={assetUrl('/assets/maya-logo.png')} alt="" width={48} height={48}/></span><span className="brand-wordmark">{t.name.toLowerCase()}<span>{t.role.toUpperCase()}</span></span></a><nav aria-label="Huvudmeny"><a href="#traning">{t.navTraining}</a><a href="#schema">{t.navSchedule}</a>{packages.length>0&&<a href="#paket">{t.navPackages}</a>}<a href="#om">{t.navAbout}</a></nav><a className="button small" href="#kontakt">{t.navCta}<ArrowUpRight size={19}/></a><button className="mobile-menu" onClick={()=>setMenu(!menu)} aria-label={menu?"Stäng meny":"Öppna meny"} aria-expanded={menu}>{menu?<X/>:<Menu/>}</button></header>
{menu&&<nav className="mobile-links" aria-label="Mobilmeny">{[['traning',t.navTraining],['schema',t.navSchedule],...(packages.length?[["paket",t.navPackages]]:[]),['om',t.navAbout],['kontakt',t.navContact]].map(([id,label])=><a key={id} href={'#'+id} onClick={()=>setMenu(false)}>{label}</a>)}</nav>}
<main id="main"><section className="hero wrap"><div className="hero-copy" data-reveal><p className="eyebrow">{t.heroEyebrow}</p><h1>{t.heroLine1}<br/>{t.heroLine2}<br/><span>{t.heroLine3}</span></h1><p className="intro">{t.heroIntro}</p><a className="button" href="#kontakt">{t.cta}<ArrowUpRight size={22}/></a><p className="micro">{t.heroMicro}</p><div className="hero-bottom"><span>{t.role.toUpperCase()}<br/>{t.name.toUpperCase()}</span><a href="#schema" aria-label="Se kommande pass"><ArrowDown size={20} aria-hidden="true"/></a></div></div><div className="hero-art" data-reveal data-motion-delay="100"><div className="hero-visual"><img src={assetUrl(c.images.hero)} alt={c.images.heroAlt} width={828} height={824} fetchPriority="high"/><div className="photo-shade"/><div className="photo-note"><span>{t.heroPhotoLabel}</span><p>{t.heroPhotoText}</p></div><div className="round-label"><Heart size={16} aria-hidden="true"/>{t.heroBadge}</div></div><div className="equipment-art" aria-hidden="true"><img src={assetUrl('/assets/fitness-sculpture.webp')} alt="" width={1000} height={833} decoding="async"/></div></div></section>
<div className="principles"><div className="wrap">{[t.principle1,t.principle2,t.principle3].map((v,i)=>{const Icon=[Target,Compass,Heart][i];return <span key={v}><Icon size={23} strokeWidth={1.65} aria-hidden="true"/>{v}</span>})}</div></div>
<Schedule t={t} now={now}/>
<section className="services wrap section" id="traning"><div className="section-heading" data-reveal><div><p className="eyebrow">{t.servicesEyebrow}</p><h2>{t.servicesTitle}</h2></div><p>{t.servicesIntro}</p></div><div className="cards">{c.services.map((s,i)=><article className="card" data-reveal data-motion-delay={i%3*75} key={s.id}><div className="card-image"><img src={assetUrl(s.image)} alt={s.alt} loading="lazy"/><span className="tag">{s.tag}</span></div><div className="card-body"><h3>{s.title}</h3><p>{s.text}</p><a href="#kontakt" className="text-link">{s.cta}<ArrowUpRight size={22}/></a></div></article>)}</div></section>
{packages.length>0&&<section className="packages wrap section" id="paket"><div className="section-heading" data-reveal><div><p className="eyebrow">{t.packagesEyebrow}</p><h2>{t.packagesTitle}</h2></div><p>{t.packagesIntro}</p></div><div className="package-grid">{packages.map(p=><article className="package-card" key={p.id} data-reveal><p className="package-category">{p.category}</p><h3>{p.title}</h3><div className="package-price">{p.price?<><strong>{p.price}</strong><span>{p.unit}</span></>:<strong className="inquiry-price">{t.packageNoPrice}</strong>}</div>{p.description&&<p className="package-description">{p.description}</p>}<a className="text-link" href={t.email?'mailto:'+t.email+'?subject='+encodeURIComponent('Förfrågan: '+p.category+' – '+p.title):phoneHref(t.phone)}>{t.packageCta}<ArrowUpRight size={18}/></a></article>)}</div></section>}
<section className="about" id="om"><div className="wrap about-grid" data-reveal><div><p className="eyebrow">{t.aboutEyebrow}</p><h2>{t.aboutTitle}</h2><Activity className="about-mark" size={64} strokeWidth={1.2} aria-hidden="true"/></div><div className="about-copy"><p className="large">{t.aboutLead}</p><p>{t.aboutText}</p><p>{t.aboutText2}</p><a className="text-link" href="#kontakt">{t.aboutCta}<ArrowUpRight size={22}/></a></div></div></section>
<section className="process wrap section"><div className="section-heading" data-reveal><div><p className="eyebrow">{t.processEyebrow}</p><h2>{t.processTitle}</h2></div><p>{t.processIntro}</p></div><div className="steps-row"><div className="steps">{c.steps.map((s,i)=><article key={i} data-reveal data-motion-delay={i%3*75}><span>{String(i+1).padStart(2,'0')}</span><h3>{s.title}</h3><p>{s.text}</p></article>)}</div><PlateStack/></div></section>
<section className="contact wrap" data-reveal id="kontakt"><div><p className="eyebrow">{t.contactEyebrow}</p><h2>{t.contactTitle}</h2><p>{t.contactText}</p><a className="button" href={phoneHref(t.phone)}>{t.call}<Phone size={21} aria-hidden="true"/></a><a className="phone" href={phoneHref(t.phone)}>{t.phone}</a>{t.email&&<a className="email-link" href={"mailto:"+t.email}><Mail size={18} aria-hidden="true"/>{t.email}</a>}</div><div className="contact-side"><img className="contact-mark" src={assetUrl('/assets/maya-logo-white.svg')} alt="" width={256} height={256} loading="lazy" aria-hidden="true"/><p>{t.role.toUpperCase()}<br/>{t.contactPlace}</p>{t.instagram&&<a href={t.instagram} target="_blank" rel="noopener noreferrer"><Camera size={17} aria-hidden="true"/>Hitta mig på Instagram<ArrowUpRight size={16} aria-hidden="true"/></a>}</div></section>
</main><footer className="wrap"><a className="brand" href="#"><span className="brand-symbol"><img src={assetUrl('/assets/maya-logo.png')} alt="" width={48} height={48}/></span><span className="brand-wordmark">{t.name.toLowerCase()}<span>{t.role.toUpperCase()}</span></span></a><p>{t.footer}</p><div>{t.instagram&&<a href={t.instagram} target="_blank" rel="noopener noreferrer"><Camera size={16} aria-hidden="true"/>Instagram</a>}{t.facebook&&<a href={t.facebook} target="_blank" rel="noopener noreferrer"><ExternalLink size={16} aria-hidden="true"/>Facebook</a>}{t.email&&<a href={"mailto:"+t.email}><Mail size={16} aria-hidden="true"/>Mejla Maya</a>}<a href={base+'admin/'}>Admin</a></div><small>© {new Date().getFullYear()} {t.name}</small></footer></div>;
}
/** Three weight plates that land one by one beside the steps: every step adds a little weight. */
const PLATES:[string,number,number][]=[['shadow0',740,232],['plate0',710,273],['shadow1',598,169],['plate1',571,206],['shadow2',470,120],['plate2',445,155]];
function PlateStack(){return <div className="plate-stack" data-plates aria-hidden="true">{PLATES.map(([name,w,h])=><img key={name} className={'plate-layer plate-'+name} src={assetUrl('/assets/plates/'+name+'.webp')} alt="" width={w} height={h} loading="lazy" decoding="async"/>)}</div>;}
function Schedule({t,now}:{t:Record<string,string>;now:string}){
const [classes,setClasses]=useState<ClassItem[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[category,setCategory]=useState('all'),[period,setPeriod]=useState('all'),[selected,setSelected]=useState<ClassItem|null>(null);
async function load(){setLoading(true);setError('');try{const r=await apiFetch('/api/classes');if(!r.ok)throw Error();const d=await r.json() as {classes:ClassItem[]};setClasses(d.classes);}catch{setError('Schemat kunde inte hämtas. Försök igen.');}finally{setLoading(false);}}
useEffect(()=>{void load();},[]);
const week=new Date(now.slice(0,10)+'T12:00:00Z');week.setUTCDate(week.getUTCDate()+7);const end=week.toISOString().slice(0,10);
const filtered=classes.filter(c=>(category==='all'||c.category===category)&&(period==='all'||(period==='today'?c.starts_at.slice(0,10)===now.slice(0,10):c.starts_at.slice(0,10)<end)));
const groups=Object.groupBy(filtered,c=>c.starts_at.slice(0,10));
return <section className="schedule section" id="schema"><div className="wrap"><div className="section-heading" data-reveal><div><p className="eyebrow">{t.scheduleEyebrow}</p><h2>{t.scheduleTitle}</h2></div><p>{t.scheduleIntro}</p></div><div className="schedule-toolbar"><div className="period-buttons" aria-label="Visa tidsperiod">{[['all','Alla kommande'],['week','Närmaste 7 dagarna'],['today','Idag']].map(([v,label])=><button key={v} aria-pressed={period===v} onClick={()=>setPeriod(v)}>{label}</button>)}</div><Select value={category} onValueChange={setCategory}><SelectTrigger aria-label="Filtrera träningsform"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">Alla träningsformer</SelectItem>{Array.from(new Set(classes.map(c=>c.category))).map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></div>
{loading?<div role="status" className="schedule-empty schedule-loading"><span className="mini-ball" aria-hidden="true"><img src={assetUrl('/assets/loader/ball.webp')} alt="" width={573} height={572}/></span>Hämtar kommande pass…</div>:error?<div className="schedule-empty" role="alert"><p>{error}</p><button className="button" onClick={load}>Försök igen</button></div>:!filtered.length?<div className="schedule-empty"><CalendarDays size={32}/><h3>{classes.length?'Inga pass för ditt val':'Nästa pass börjar här.'}</h3><p>{classes.length?'Välj en annan tidsperiod eller träningsform.':t.scheduleEmpty}</p>{classes.length?<button className="text-link" onClick={()=>{setCategory('all');setPeriod('all');}}>Visa alla pass</button>:<a className="text-link" href="#kontakt">Kontakta Maya <ArrowUpRight size={20}/></a>}</div>:<div className="timeline" key={period+category}>{Object.entries(groups).map(([day,items])=><div className="timeline-day" key={day}><div className="day-label"><span>{new Date(day+'T12:00:00Z').getUTCDate()}</span><p>{dateLabel(day).replace(/^\S+ \d+ /,'')}<br/>{dateLabel(day).split(' ')[0]}</p></div><div className="day-classes">{items?.map(c=><button key={c.id} className={'class-row '+(c.status==='cancelled'?'cancelled':'')} onClick={()=>setSelected(c)}><div className="class-time">{c.starts_at.slice(11)}<span>{c.duration} min</span></div><div className="class-info"><span className="class-category">{c.category}</span><h3>{c.title}</h3><p><MapPin size={14}/>{c.location}</p></div><span className="class-status">{c.status==='cancelled'?'Inställt':c.price||'Se detaljer'}</span><ArrowUpRight className="row-arrow" size={22}/></button>)}</div></div>)}</div>}
<p className="timezone">Alla tider visas i svensk tid.</p></div><Dialog open={!!selected} onOpenChange={v=>{if(!v)setSelected(null);}}><DialogContent className="class-dialog">{selected&&<><p className="eyebrow">{selected.category}</p><DialogTitle>{selected.title}</DialogTitle><DialogDescription>{dateLabel(selected.starts_at)}</DialogDescription><div className="detail-facts"><p><Clock size={18}/>{selected.starts_at.slice(11)} · {selected.duration} min</p><p><MapPin size={18}/>{selected.location}</p></div><p className="whitespace-pre-wrap">{selected.description}</p>{selected.price&&<p><strong>{selected.price}</strong></p>}{selected.status==='cancelled'?<p role="status" className="cancel-note">Det här passet är inställt.</p>:<a className="button" href={selected.booking_url||phoneHref(t.phone)} target={selected.booking_url?'_blank':undefined} rel={selected.booking_url?'noopener noreferrer':undefined}>{selected.booking_url?'Till bokningen':'Ring för att boka'}<ArrowUpRight size={20}/></a>}</>}</DialogContent></Dialog></section>;
}
