'use client';
import {useMemo,useState} from 'react';
import {Search,X,ArrowUpRight} from 'lucide-react';
import {contentFields,searchContent,type ContentField} from '@/lib/content-search';
import type {SiteContent} from '@/lib/content';
function excerpt(value:string,query:string){const flat=value.toLocaleLowerCase('sv').normalize('NFD').replace(/[\u0300-\u036f]/g,'');const words=query.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').split(/\s+/).filter(w=>w.length>2);const positions=words.map(w=>flat.indexOf(w)).filter(i=>i>=0);const start=positions.length?Math.max(0,Math.min(...positions)-65):0;return (start?'…':'')+value.slice(start,start+220)+(value.length>start+220?'…':'');}
export function ContentSearch({content,onSelect}:{content:SiteContent;onSelect:(field:ContentField)=>void}){
 const [query,setQuery]=useState(''),[limit,setLimit]=useState(8);
 const results=useMemo(()=>searchContent(contentFields(content),query),[content,query]);
 return <section className="content-search" aria-label="Hitta text att redigera"><label htmlFor="content-query">Hitta en text på hemsidan</label><div className="content-search-input"><Search size={21} aria-hidden="true"/><input id="content-query" type="search" value={query} maxLength={160} onChange={e=>{setQuery(e.target.value);setLimit(8);}} placeholder="Sök en fras, rubrik eller t.ex. mejl…" aria-describedby="content-search-help"/>{query&&<button type="button" aria-label="Rensa textsökningen" onClick={()=>setQuery('')}><X size={18}/></button>}</div><p id="content-search-help">Söker i texter, paket och bildbeskrivningar. Mindre stavfel och å, ä, ö fungerar också.</p>{query.trim()&&<><p role="status" className="search-count">{results.length?`${results.length} ${results.length===1?'träff':'träffar'}. Välj en för att öppna rätt fält.`:'Ingen träff. Prova ett kortare ord eller en del av texten.'}</p><div className="content-search-results">{results.slice(0,limit).map(r=><button key={r.id} type="button" className="content-search-result" onClick={()=>onSelect(r)}><span className="search-result-location">{r.section}{r.hidden&&<small>Dolt paket</small>}{r.similar&&<small>Liknande träff</small>}</span><strong>{r.label}<ArrowUpRight size={17}/></strong><span className="search-result-value">{r.value?excerpt(r.value,query):'Tomt fält'}</span><span className="search-result-action">Öppna och redigera</span></button>)}</div>{results.length>limit&&<button type="button" className="admin-button secondary" onClick={()=>setLimit(limit+12)}>Visa fler träffar ({results.length-limit} kvar)</button>}</>}</section>;
}
