'use client';
import {Plus,Trash2,Package,Globe,ChevronDown} from 'lucide-react';
import {Switch} from '@/components/ui/switch';
import {type TrainingPackage} from '@/lib/content';
export function PackageEditor({packages,onChange,onRemove}:{packages:TrainingPackage[];onChange:(packages:TrainingPackage[])=>void;onRemove:(id:string)=>void}){
 function patch(id:string,change:Partial<TrainingPackage>){onChange(packages.map(p=>p.id===id?{...p,...change}:p));}
 function add(online=false){onChange([...packages,{id:crypto.randomUUID(),title:online?'Online PT':'Nytt paket',category:online?'Online PT':'Personlig träning',price:'',unit:online?'kr / månad':'kr / paket',description:'',published:false}]);}
 return <div className="package-editor"><div className="package-editor-actions"><button type="button" className="admin-button" disabled={packages.length>=30} onClick={()=>add()}><Plus size={17}/>Lägg till paket</button><button type="button" className="admin-button secondary" disabled={packages.length>=30} onClick={()=>add(true)}><Globe size={17}/>Lägg till onlinepaket</button></div>{!packages.length&&<p>Inga paket ännu. Lägg till ditt första paket ovan.</p>}{packages.map(p=><details className="editor-section package-edit" key={p.id}><summary><Package size={20} aria-hidden="true"/><div><strong>{p.title}</strong><small>{p.category} · {p.price?p.price+' '+p.unit:'Pris ej angivet'} · {p.published?'Visas efter publicering':'Dolt utkast'}</small></div><ChevronDown size={18} className="summary-chevron" aria-hidden="true"/></summary><div className="editor-fields"><div className="form-columns"><label className="field"><span>Paketets namn</span><input id={"package-"+p.id+"-title"} value={p.title} maxLength={100} onChange={e=>patch(p.id,{title:e.target.value})}/></label><label className="field"><span>Träningsform</span><input list="package-categories" id={"package-"+p.id+"-category"} value={p.category} maxLength={60} onChange={e=>patch(p.id,{category:e.target.value})}/></label><label className="field"><span>Pris</span><input placeholder="Till exempel 3 250" id={"package-"+p.id+"-price"} value={p.price} maxLength={60} onChange={e=>patch(p.id,{price:e.target.value})}/><small>Tomt fält visar ”Kontakta för pris”.</small></label><label className="field"><span>Priset gäller</span><input list="package-units" placeholder="kr / paket" id={"package-"+p.id+"-unit"} value={p.unit} maxLength={60} onChange={e=>patch(p.id,{unit:e.target.value})}/></label></div><label className="field"><span>Vad ingår?</span><textarea rows={4} placeholder="Beskriv antal pass, uppföljning och vad kunden får." id={"package-"+p.id+"-description"} value={p.description} maxLength={1500} onChange={e=>patch(p.id,{description:e.target.value})}/></label><div className="package-edit-footer"><label><Switch aria-label={"Visa "+p.title+" på hemsidan"} checked={p.published} onCheckedChange={published=>patch(p.id,{published})}/><span>Visa paketet på hemsidan</span></label><button type="button" className="plain-button" onClick={()=>onRemove(p.id)}><Trash2 size={16}/>Ta bort paket</button></div></div></details>)}<datalist id="package-categories">{['Personlig träning','PT Duo','Online PT','Gruppträning','Presentkort'].map(v=><option key={v}>{v}</option>)}</datalist><datalist id="package-units">{['kr / paket','kr / person','kr / timme','kr / månad'].map(v=><option key={v}>{v}</option>)}</datalist></div>;
}
